#!/bin/sh

i3lock \
  --clock \
  --indicator \
  --inside-color=00000088 \
  --ring-color=ffffff55 \
  --line-color=00000000 \
  --keyhl-color=00ff0055 \
  --bshl-color=ff000055 \
  --separator-color=00000000 \
  --time-color=ffffff \
  --date-color=ffffff \
  --verif-color=ffffff \
  --wrong-color=ff5555 \
  --time-str="%H:%M" \
  --date-str="%a %d %b"

