#!/bin/sh
# Display Network

interface="$(ip route | awk '/default/ {print $5; exit}')"

[ -z "$interface" ] && {
	echo " Disconnected"
	exit 0
}

ip_addr="$(ip -4 -o addr show $interface | awk '{print $4}' | sed 's/\/.*//')"


if [ -d "/sys/class/net/$interface/wireless" ]; then
	ssid="$(nmcli -t -f ACTIVE,SSID,SIGNAL device wifi | awk -F: '$1=="yes"{print $2}')"
	signal="$(nmcli -t -f ACTIVE,SSID,SIGNAL device wifi | awk -F: '$1=="yes"{print $3}')"

 	[ -z "$ssid" ] && ssid="WiFi"
  	[ -z "$signal" ] && signal=0

	if [ "$signal" -gt 80 ]; then
		icon=󰤨
	elif [ "$signal" -gt 60 ]; then
		icon=󰤥
	elif [ "$signal" -gt 40 ]; then
		icon=󰤢
	elif [ "$signal" -gt 20 ]; then
		icon=󰤟
	else
		icon=󰤯
	fi

	echo "$icon $ssid $ip_addr"
else
	echo "󰈀  $ip_addr"
fi

