windowrule {
    name = firefox_display
    match:class = ^(firefox)$

    workspace = 2
}

windowrule {
    name = brave_display
    match:class = ^(brave-browser)$

    workspace = 3
}

windowrule {
    name = summoners_war
    match:class = ^(steam_app_2426960)$

    render_unfocused = true
    workspace = 9
}

windowrule {
    name = Minecraft
    match:class = ^Minecraft.*$
    # render_unfocused = true
    workspace = 4
}
